version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - ml
    restart: unless-stopped
    # Add volumes if you want live reload in dev

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    volumes:
      - ./ml:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./ml/.env
    command: ["bash"]
    tty: true
    # Uncomment below to mount code for dev
    # volumes:
    #   - ./ml:/ml
